# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
env:
  hook: ${{ secrets.DISCORD_HOOK }}
  path: testDirectory\logs

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install Chrome
      run: sudo apt-get install -y chromium-browser
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    
    - name: Test with pytest
      run: pytest test_web.py
    - name: upload artifacts
      uses: actions/upload-artifacts@v1.0.0
      with:
        name: logs
        path: ${{ env.path }}
  
  report:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v2
      with:
        name: logs
        path: ${{ env.path }}
    - name: setup python
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install discord requests python-dotenv
    - name: send logs
      run: python sendLogs.py
        
